-- =========================================================
-- HUVANG DATABASE V2
-- Hỗ trợ nhiều nguồn giá: PNJ, MI_HONG, SJC, DOJI...
-- =========================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- =========================================================
-- 1. Danh mục nguồn cung cấp giá
-- =========================================================

CREATE TABLE public.gold_price_sources (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    code VARCHAR(30) NOT NULL,
    name VARCHAR(100) NOT NULL,

    website_url TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT gold_price_sources_code_key UNIQUE (code)
);

COMMENT ON TABLE public.gold_price_sources
IS 'Danh sách nguồn cung cấp giá vàng như PNJ, MI_HONG, SJC, DOJI';

COMMENT ON COLUMN public.gold_price_sources.code
IS 'Mã nguồn dùng trong chương trình, ví dụ PNJ, MI_HONG, SJC';


-- =========================================================
-- 2. Danh mục loại vàng chuẩn
-- Dùng để so sánh sản phẩm tương đương giữa nhiều nguồn
-- =========================================================

CREATE TABLE public.gold_types (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    code VARCHAR(50) NOT NULL,
    name VARCHAR(150) NOT NULL,

    purity NUMERIC(6,3),
    unit VARCHAR(30) NOT NULL DEFAULT 'chi',

    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT gold_types_code_key UNIQUE (code)
);

COMMENT ON TABLE public.gold_types
IS 'Danh mục loại vàng chuẩn dùng chung để so sánh giữa các nguồn';

COMMENT ON COLUMN public.gold_types.purity
IS 'Hàm lượng vàng, ví dụ 999.900 hoặc 750.000';


-- =========================================================
-- 3. Sản phẩm thực tế của từng nguồn
-- =========================================================

CREATE TABLE public.gold_source_products (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    source_id UUID NOT NULL,
    gold_type_id UUID,

    product_code VARCHAR(100) NOT NULL,
    product_name VARCHAR(255) NOT NULL,

    source_unit VARCHAR(30) NOT NULL DEFAULT 'chi',
    conversion_to_chi NUMERIC(12,6) NOT NULL DEFAULT 1,

    display_order INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT gold_source_products_source_fk
        FOREIGN KEY (source_id)
        REFERENCES public.gold_price_sources(id)
        ON DELETE CASCADE,

    CONSTRAINT gold_source_products_gold_type_fk
        FOREIGN KEY (gold_type_id)
        REFERENCES public.gold_types(id)
        ON DELETE SET NULL,

    CONSTRAINT gold_source_products_source_product_key
        UNIQUE (source_id, product_code)
);

COMMENT ON TABLE public.gold_source_products
IS 'Danh sách sản phẩm vàng cụ thể được công bố bởi từng nguồn';

COMMENT ON COLUMN public.gold_source_products.conversion_to_chi
IS 'Hệ số đổi đơn vị nguồn về chỉ; ví dụ 1 lượng = 10 chỉ';


-- =========================================================
-- 4. Giá mới nhất
-- Mỗi sản phẩm của mỗi nguồn chỉ có một dòng
-- =========================================================

CREATE TABLE public.gold_price_latest (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    source_product_id UUID NOT NULL,

    buy_price NUMERIC(18,2),
    sell_price NUMERIC(18,2),

    source_updated_at TIMESTAMPTZ,
    fetched_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    raw_data JSONB,

    CONSTRAINT gold_price_latest_product_fk
        FOREIGN KEY (source_product_id)
        REFERENCES public.gold_source_products(id)
        ON DELETE CASCADE,

    CONSTRAINT gold_price_latest_product_key
        UNIQUE (source_product_id),

    CONSTRAINT gold_price_latest_buy_price_check
        CHECK (buy_price IS NULL OR buy_price >= 0),

    CONSTRAINT gold_price_latest_sell_price_check
        CHECK (sell_price IS NULL OR sell_price >= 0)
);

COMMENT ON TABLE public.gold_price_latest
IS 'Lưu giá mua và giá bán mới nhất của từng sản phẩm';

COMMENT ON COLUMN public.gold_price_latest.raw_data
IS 'Dữ liệu gốc do website hoặc API nguồn trả về, dùng để kiểm tra lỗi';


-- =========================================================
-- 5. Lịch sử giá
-- =========================================================

CREATE TABLE public.gold_price_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    source_product_id UUID NOT NULL,

    buy_price NUMERIC(18,2),
    sell_price NUMERIC(18,2),

    source_updated_at TIMESTAMPTZ,
    fetched_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    raw_data JSONB,

    CONSTRAINT gold_price_history_product_fk
        FOREIGN KEY (source_product_id)
        REFERENCES public.gold_source_products(id)
        ON DELETE CASCADE,

    CONSTRAINT gold_price_history_buy_price_check
        CHECK (buy_price IS NULL OR buy_price >= 0),

    CONSTRAINT gold_price_history_sell_price_check
        CHECK (sell_price IS NULL OR sell_price >= 0)
);

COMMENT ON TABLE public.gold_price_history
IS 'Lưu toàn bộ lịch sử thay đổi giá của tất cả nguồn';


-- =========================================================
-- 6. Nhật ký chạy chức năng lấy giá
-- =========================================================

CREATE TABLE public.gold_price_fetch_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    source_id UUID,

    status VARCHAR(20) NOT NULL,
    message TEXT,

    products_received INTEGER NOT NULL DEFAULT 0,
    products_updated INTEGER NOT NULL DEFAULT 0,

    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    finished_at TIMESTAMPTZ,

    error_detail JSONB,

    CONSTRAINT gold_price_fetch_logs_source_fk
        FOREIGN KEY (source_id)
        REFERENCES public.gold_price_sources(id)
        ON DELETE SET NULL,

    CONSTRAINT gold_price_fetch_logs_status_check
        CHECK (status IN ('RUNNING', 'SUCCESS', 'PARTIAL', 'FAILED'))
);

COMMENT ON TABLE public.gold_price_fetch_logs
IS 'Nhật ký mỗi lần Edge Function lấy dữ liệu giá vàng';


-- =========================================================
-- 7. Index
-- =========================================================

CREATE INDEX gold_source_products_source_id_idx
ON public.gold_source_products(source_id);

CREATE INDEX gold_source_products_gold_type_id_idx
ON public.gold_source_products(gold_type_id);

CREATE INDEX gold_price_latest_source_product_id_idx
ON public.gold_price_latest(source_product_id);

CREATE INDEX gold_price_history_product_time_idx
ON public.gold_price_history(source_product_id, fetched_at DESC);

CREATE INDEX gold_price_history_fetched_at_idx
ON public.gold_price_history(fetched_at DESC);

CREATE INDEX gold_price_fetch_logs_source_time_idx
ON public.gold_price_fetch_logs(source_id, started_at DESC);


-- =========================================================
-- 8. Hàm tự động cập nhật updated_at
-- =========================================================

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;


-- =========================================================
-- 9. Trigger updated_at
-- =========================================================

CREATE TRIGGER set_gold_price_sources_updated_at
BEFORE UPDATE ON public.gold_price_sources
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER set_gold_types_updated_at
BEFORE UPDATE ON public.gold_types
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER set_gold_source_products_updated_at
BEFORE UPDATE ON public.gold_source_products
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER set_gold_price_latest_updated_at
BEFORE UPDATE ON public.gold_price_latest
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();


-- =========================================================
-- 10. Dữ liệu nguồn mặc định
-- =========================================================

INSERT INTO public.gold_price_sources (
    code,
    name,
    website_url
)
VALUES
    ('PNJ', 'Phú Nhuận Jewelry', 'https://www.pnj.com.vn'),
    ('MI_HONG', 'Vàng Mi Hồng', 'https://mihong.vn'),
    ('SJC', 'Công ty Vàng bạc Đá quý Sài Gòn', 'https://sjc.com.vn')
ON CONFLICT (code) DO NOTHING;


-- =========================================================
-- 11. Loại vàng chuẩn ban đầu
-- Có thể bổ sung sau khi xem dữ liệu thật của từng nguồn
-- =========================================================

INSERT INTO public.gold_types (
    code,
    name,
    purity,
    unit
)
VALUES
    ('GOLD_9999_RING', 'Nhẫn trơn vàng 9999', 999.900, 'chi'),
    ('GOLD_9999_BAR', 'Vàng miếng 9999', 999.900, 'chi'),
    ('GOLD_24K', 'Vàng 24K', 999.000, 'chi'),
    ('GOLD_18K', 'Vàng 18K', 750.000, 'chi'),
    ('GOLD_14K', 'Vàng 14K', 585.000, 'chi'),
    ('GOLD_10K', 'Vàng 10K', 417.000, 'chi')
ON CONFLICT (code) DO NOTHING;

-- =========================================================
-- 12. Hồ sơ người dùng
-- Liên kết với auth.users của Supabase
-- =========================================================

CREATE TABLE public.profiles (
    id UUID PRIMARY KEY,

    email TEXT,
    full_name VARCHAR(150),
    avatar_url TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT profiles_user_fk
        FOREIGN KEY (id)
        REFERENCES auth.users(id)
        ON DELETE CASCADE
);

COMMENT ON TABLE public.profiles
IS 'Thông tin mở rộng của người dùng Supabase Auth';


CREATE TRIGGER set_profiles_updated_at
BEFORE UPDATE ON public.profiles
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();


-- =========================================================
-- 13. Giao dịch mua bán vàng
-- =========================================================

CREATE TABLE public.gold_transactions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    user_id UUID NOT NULL,

    transaction_type VARCHAR(10) NOT NULL,

    gold_type_id UUID,
    source_product_id UUID,

    gold_name VARCHAR(255) NOT NULL,

    quantity_chi NUMERIC(18,6) NOT NULL,
    unit_price NUMERIC(18,2) NOT NULL,

    fee_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
    total_amount NUMERIC(18,2) NOT NULL,

    transaction_date DATE NOT NULL DEFAULT CURRENT_DATE,

    seller_name VARCHAR(255),
    invoice_code VARCHAR(100),
    note TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT gold_transactions_user_fk
        FOREIGN KEY (user_id)
        REFERENCES auth.users(id)
        ON DELETE CASCADE,

    CONSTRAINT gold_transactions_gold_type_fk
        FOREIGN KEY (gold_type_id)
        REFERENCES public.gold_types(id)
        ON DELETE SET NULL,

    CONSTRAINT gold_transactions_source_product_fk
        FOREIGN KEY (source_product_id)
        REFERENCES public.gold_source_products(id)
        ON DELETE SET NULL,

    CONSTRAINT gold_transactions_type_check
        CHECK (transaction_type IN ('BUY', 'SELL')),

    CONSTRAINT gold_transactions_quantity_check
        CHECK (quantity_chi > 0),

    CONSTRAINT gold_transactions_unit_price_check
        CHECK (unit_price >= 0),

    CONSTRAINT gold_transactions_fee_check
        CHECK (fee_amount >= 0),

    CONSTRAINT gold_transactions_total_check
        CHECK (total_amount >= 0)
);

COMMENT ON TABLE public.gold_transactions
IS 'Lưu giao dịch mua và bán vàng của từng người dùng';

COMMENT ON COLUMN public.gold_transactions.quantity_chi
IS 'Khối lượng giao dịch đã quy đổi về đơn vị chỉ';

COMMENT ON COLUMN public.gold_transactions.unit_price
IS 'Đơn giá trên một chỉ tại thời điểm giao dịch';

COMMENT ON COLUMN public.gold_transactions.total_amount
IS 'Tổng tiền thực tế của giao dịch, bao gồm hoặc trừ phí tùy cách người dùng nhập';


CREATE INDEX gold_transactions_user_date_idx
ON public.gold_transactions(user_id, transaction_date DESC);

CREATE INDEX gold_transactions_user_gold_type_idx
ON public.gold_transactions(user_id, gold_type_id);

CREATE INDEX gold_transactions_source_product_idx
ON public.gold_transactions(source_product_id);


CREATE TRIGGER set_gold_transactions_updated_at
BEFORE UPDATE ON public.gold_transactions
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();


-- =========================================================
-- 14. Cấu hình theo dõi giá của người dùng
-- =========================================================

CREATE TABLE public.user_gold_preferences (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    user_id UUID NOT NULL,
    gold_type_id UUID NOT NULL,

    preferred_source_id UUID,
    preferred_source_product_id UUID,

    manual_buy_price NUMERIC(18,2),
    manual_sell_price NUMERIC(18,2),

    use_manual_price BOOLEAN NOT NULL DEFAULT FALSE,
    is_favorite BOOLEAN NOT NULL DEFAULT TRUE,
    display_order INTEGER NOT NULL DEFAULT 0,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT user_gold_preferences_user_fk
        FOREIGN KEY (user_id)
        REFERENCES auth.users(id)
        ON DELETE CASCADE,

    CONSTRAINT user_gold_preferences_gold_type_fk
        FOREIGN KEY (gold_type_id)
        REFERENCES public.gold_types(id)
        ON DELETE CASCADE,

    CONSTRAINT user_gold_preferences_source_fk
        FOREIGN KEY (preferred_source_id)
        REFERENCES public.gold_price_sources(id)
        ON DELETE SET NULL,

    CONSTRAINT user_gold_preferences_product_fk
        FOREIGN KEY (preferred_source_product_id)
        REFERENCES public.gold_source_products(id)
        ON DELETE SET NULL,

    CONSTRAINT user_gold_preferences_user_type_key
        UNIQUE (user_id, gold_type_id),

    CONSTRAINT user_gold_preferences_manual_buy_check
        CHECK (manual_buy_price IS NULL OR manual_buy_price >= 0),

    CONSTRAINT user_gold_preferences_manual_sell_check
        CHECK (manual_sell_price IS NULL OR manual_sell_price >= 0)
);

COMMENT ON TABLE public.user_gold_preferences
IS 'Nguồn giá ưu tiên và giá thủ công của từng loại vàng theo từng người dùng';


CREATE INDEX user_gold_preferences_user_idx
ON public.user_gold_preferences(user_id);


CREATE TRIGGER set_user_gold_preferences_updated_at
BEFORE UPDATE ON public.user_gold_preferences
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();


-- =========================================================
-- 15. Tin nhắn AI
-- =========================================================

CREATE TABLE public.chat_messages (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    user_id UUID NOT NULL,

    role VARCHAR(20) NOT NULL,
    content TEXT NOT NULL,

    metadata JSONB,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chat_messages_user_fk
        FOREIGN KEY (user_id)
        REFERENCES auth.users(id)
        ON DELETE CASCADE,

    CONSTRAINT chat_messages_role_check
        CHECK (role IN ('user', 'assistant', 'system'))
);

COMMENT ON TABLE public.chat_messages
IS 'Lịch sử hội thoại giữa người dùng và trợ lý AI';


CREATE INDEX chat_messages_user_time_idx
ON public.chat_messages(user_id, created_at DESC);


-- =========================================================
-- 16. Cấu hình chung của hệ thống
-- =========================================================

CREATE TABLE public.app_settings (
    setting_key VARCHAR(100) PRIMARY KEY,
    setting_value JSONB NOT NULL DEFAULT '{}'::JSONB,

    description TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE public.app_settings
IS 'Cấu hình chung của ứng dụng, chỉ phía quản trị hoặc Edge Function được sửa';


CREATE TRIGGER set_app_settings_updated_at
BEFORE UPDATE ON public.app_settings
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();


-- =========================================================
-- 17. Tự động tạo profile khi đăng ký tài khoản
-- =========================================================

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    INSERT INTO public.profiles (
        id,
        email,
        full_name,
        avatar_url
    )
    VALUES (
        NEW.id,
        NEW.email,
        COALESCE(
            NEW.raw_user_meta_data ->> 'full_name',
            NEW.raw_user_meta_data ->> 'name'
        ),
        NEW.raw_user_meta_data ->> 'avatar_url'
    )
    ON CONFLICT (id) DO NOTHING;

    RETURN NEW;
END;
$$;


CREATE TRIGGER on_auth_user_created
AFTER INSERT ON auth.users
FOR EACH ROW
EXECUTE FUNCTION public.handle_new_user();


-- =========================================================
-- 18. View tổng hợp số vàng đang sở hữu
-- BUY cộng vào, SELL trừ ra
-- =========================================================

CREATE OR REPLACE VIEW public.user_gold_holdings
WITH (security_invoker = true)
AS
SELECT
    gt.user_id,
    gt.gold_type_id,

    COALESCE(gtype.code, 'UNCLASSIFIED') AS gold_type_code,
    COALESCE(gtype.name, gt.gold_name) AS gold_type_name,

    SUM(
        CASE
            WHEN gt.transaction_type = 'BUY'
                THEN gt.quantity_chi
            WHEN gt.transaction_type = 'SELL'
                THEN -gt.quantity_chi
            ELSE 0
        END
    ) AS quantity_chi,

    SUM(
        CASE
            WHEN gt.transaction_type = 'BUY'
                THEN gt.total_amount
            WHEN gt.transaction_type = 'SELL'
                THEN -gt.total_amount
            ELSE 0
        END
    ) AS net_invested_amount,

    MAX(gt.transaction_date) AS latest_transaction_date

FROM public.gold_transactions gt

LEFT JOIN public.gold_types gtype
    ON gtype.id = gt.gold_type_id

GROUP BY
    gt.user_id,
    gt.gold_type_id,
    gtype.code,
    gtype.name,
    gt.gold_name

HAVING SUM(
    CASE
        WHEN gt.transaction_type = 'BUY'
            THEN gt.quantity_chi
        WHEN gt.transaction_type = 'SELL'
            THEN -gt.quantity_chi
        ELSE 0
    END
) <> 0;

COMMENT ON VIEW public.user_gold_holdings
IS 'Tổng hợp số lượng vàng hiện đang sở hữu từ lịch sử mua bán';

-- =========================================================
-- 19. Bật Row Level Security
-- =========================================================

ALTER TABLE public.profiles
ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.gold_transactions
ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.user_gold_preferences
ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.chat_messages
ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.gold_price_sources
ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.gold_types
ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.gold_source_products
ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.gold_price_latest
ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.gold_price_history
ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.gold_price_fetch_logs
ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.app_settings
ENABLE ROW LEVEL SECURITY;


-- =========================================================
-- 20. Policy cho profiles
-- Người dùng chỉ xem và sửa profile của chính mình
-- =========================================================

CREATE POLICY profiles_select_own
ON public.profiles
FOR SELECT
TO authenticated
USING (id = auth.uid());

CREATE POLICY profiles_update_own
ON public.profiles
FOR UPDATE
TO authenticated
USING (id = auth.uid())
WITH CHECK (id = auth.uid());


-- =========================================================
-- 21. Policy cho gold_transactions
-- Người dùng chỉ thao tác giao dịch của chính mình
-- =========================================================

CREATE POLICY gold_transactions_select_own
ON public.gold_transactions
FOR SELECT
TO authenticated
USING (user_id = auth.uid());

CREATE POLICY gold_transactions_insert_own
ON public.gold_transactions
FOR INSERT
TO authenticated
WITH CHECK (user_id = auth.uid());

CREATE POLICY gold_transactions_update_own
ON public.gold_transactions
FOR UPDATE
TO authenticated
USING (user_id = auth.uid())
WITH CHECK (user_id = auth.uid());

CREATE POLICY gold_transactions_delete_own
ON public.gold_transactions
FOR DELETE
TO authenticated
USING (user_id = auth.uid());


-- =========================================================
-- 22. Policy cho user_gold_preferences
-- =========================================================

CREATE POLICY user_gold_preferences_select_own
ON public.user_gold_preferences
FOR SELECT
TO authenticated
USING (user_id = auth.uid());

CREATE POLICY user_gold_preferences_insert_own
ON public.user_gold_preferences
FOR INSERT
TO authenticated
WITH CHECK (user_id = auth.uid());

CREATE POLICY user_gold_preferences_update_own
ON public.user_gold_preferences
FOR UPDATE
TO authenticated
USING (user_id = auth.uid())
WITH CHECK (user_id = auth.uid());

CREATE POLICY user_gold_preferences_delete_own
ON public.user_gold_preferences
FOR DELETE
TO authenticated
USING (user_id = auth.uid());


-- =========================================================
-- 23. Policy cho chat_messages
-- =========================================================

CREATE POLICY chat_messages_select_own
ON public.chat_messages
FOR SELECT
TO authenticated
USING (user_id = auth.uid());

CREATE POLICY chat_messages_insert_own
ON public.chat_messages
FOR INSERT
TO authenticated
WITH CHECK (user_id = auth.uid());

CREATE POLICY chat_messages_delete_own
ON public.chat_messages
FOR DELETE
TO authenticated
USING (user_id = auth.uid());


-- =========================================================
-- 24. Policy đọc dữ liệu thị trường
-- Người đăng nhập được phép xem
-- Frontend không được sửa trực tiếp
-- =========================================================

CREATE POLICY gold_price_sources_select_authenticated
ON public.gold_price_sources
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY gold_types_select_authenticated
ON public.gold_types
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY gold_source_products_select_authenticated
ON public.gold_source_products
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY gold_price_latest_select_authenticated
ON public.gold_price_latest
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY gold_price_history_select_authenticated
ON public.gold_price_history
FOR SELECT
TO authenticated
USING (true);


-- =========================================================
-- 25. Policy cho nhật ký lấy giá
-- Cho phép người đăng nhập xem để kiểm tra trạng thái
-- Không được sửa từ frontend
-- =========================================================

CREATE POLICY gold_price_fetch_logs_select_authenticated
ON public.gold_price_fetch_logs
FOR SELECT
TO authenticated
USING (true);


-- =========================================================
-- 26. app_settings
-- Chỉ cho phép đọc từ authenticated
-- Không cho frontend INSERT/UPDATE/DELETE
-- =========================================================

CREATE POLICY app_settings_select_authenticated
ON public.app_settings
FOR SELECT
TO authenticated
USING (true);


-- =========================================================
-- 27. Quyền thực thi function tạo profile
-- =========================================================

REVOKE ALL ON FUNCTION public.handle_new_user() FROM PUBLIC;

GRANT EXECUTE
ON FUNCTION public.handle_new_user()
TO service_role;


-- =========================================================
-- 28. Quyền sử dụng schema và bảng
-- =========================================================

GRANT USAGE ON SCHEMA public
TO authenticated;

GRANT SELECT, INSERT, UPDATE, DELETE
ON public.profiles
TO authenticated;

GRANT SELECT, INSERT, UPDATE, DELETE
ON public.gold_transactions
TO authenticated;

GRANT SELECT, INSERT, UPDATE, DELETE
ON public.user_gold_preferences
TO authenticated;

GRANT SELECT, INSERT, DELETE
ON public.chat_messages
TO authenticated;

GRANT SELECT
ON public.gold_price_sources
TO authenticated;

GRANT SELECT
ON public.gold_types
TO authenticated;

GRANT SELECT
ON public.gold_source_products
TO authenticated;

GRANT SELECT
ON public.gold_price_latest
TO authenticated;

GRANT SELECT
ON public.gold_price_history
TO authenticated;

GRANT SELECT
ON public.gold_price_fetch_logs
TO authenticated;

GRANT SELECT
ON public.app_settings
TO authenticated;


-- =========================================================
-- 29. Quyền cho service_role
-- Edge Function dùng service_role để ghi dữ liệu thị trường
-- =========================================================

GRANT ALL
ON public.gold_price_sources
TO service_role;

GRANT ALL
ON public.gold_types
TO service_role;

GRANT ALL
ON public.gold_source_products
TO service_role;

GRANT ALL
ON public.gold_price_latest
TO service_role;

GRANT ALL
ON public.gold_price_history
TO service_role;

GRANT ALL
ON public.gold_price_fetch_logs
TO service_role;

GRANT ALL
ON public.app_settings
TO service_role;

GRANT USAGE, SELECT
ON ALL SEQUENCES IN SCHEMA public
TO service_role;